# Pandas

## Task 1

You should import the necessary libraries. You will use `numpy` and `pandas` libraries.


> Don't forget to import `numpy`, and `pandas` in short form.

In [1]:
import numpy as np
import pandas as pd

## Task 2

Create a `DataFrame` from the given dictionary `data`.

In [3]:
data = {
    "Name": ["John", "Emily", "Ryan"],
    "Age": [16, 28, 22],
    "City": ["New York", "Los Angeles", "Chicago"],
}

df = pd.DataFrame(data)

## Task 3

In this task you should complete the following steps:

### Task 3.1
Display all data for `Age` column for the DataFrame you created in the previous task.

In [4]:
df["Age"]

0    16
1    28
2    22
Name: Age, dtype: int64

### Task 3.2

Add `Salary` column to the `DataFrame` with the values `[50000, 60000, 45000]`.

In [8]:
df["Salary"] = [50000, 60000, 45000]

### Task 3.3

Filter the `DataFrame` to show only the rows with the `Age` greater than 18.

In [17]:
df[df["Age"] > 18]

    Name  Age         City  Salary  Birth year
1  Emily   28  Los Angeles   60000        1997
2   Ryan   22      Chicago   45000        2003

## Task 4

In this task you should complete the following steps:

### Task 4.1

Add new calculated field `Birth year`;

In [18]:
df["Birth year"] = 2025 - df["Age"]

### Task 4.2

Add new calculated field `Average age`.

In [21]:
df["Average age"] = df["Age"].mean()

### Task 4.3

Calculate absolute difference between `Age` and `Average age`.

In [25]:
abs(df["Age"] - df["Average age"]).rename("Age difference")

0    6.0
1    6.0
2    0.0
Name: Age difference, dtype: float64

## Task 5

Complete the following tasks described below.

### Task 5.1

You have two dictionaries `data1` and `data2`. Create two `DataFrame` objects from these dictionaries. Then, `concatenate`, and `merge` these two `DataFrame` objects into one `DataFrame` object, and see the difference.

In [31]:
# Data
data1 = {'Name': ['John', 'Emily', 'Ryan'],
         'Age': [25, 28, 22]}
data2 = {'Name': ['Emily', 'Ryan', 'Mike'],
         'City': ['Los Angeles', 'Chicago', 'Houston']}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [44]:
df1.merge(df2, how="outer", copy=False)

    Name   Age         City
0  Emily  28.0  Los Angeles
1   John  25.0          NaN
2   Mike   NaN      Houston
3   Ryan  22.0      Chicago

In [46]:
pd.concat([df1, df2], copy=False)

    Name   Age         City
0   John  25.0          NaN
1  Emily  28.0          NaN
2   Ryan  22.0          NaN
0  Emily   NaN  Los Angeles
1   Ryan   NaN      Chicago
2   Mike   NaN      Houston

### Task 5.2

You have two `Series` objects `s1` and `s2`. Make default mathematical operations on these two `Series` objects. Such as `+`, `-`, `*`, `/`, `**`, `//`, `%`. Also, filter `s1` and print only even numbers, and `s2` only with odd numbers.

In [47]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])

In [49]:
(s1 + s2).rename("Sum")

0     7
1     9
2    11
3    13
4    15
Name: Sum, dtype: int64

In [50]:
(s1 - s2).rename("Dif")

0   -5
1   -5
2   -5
3   -5
4   -5
Name: Dif, dtype: int64

In [51]:
(s1 * s2).rename("Multiply")

0     6
1    14
2    24
3    36
4    50
Name: Multiply, dtype: int64

In [52]:
(s1 / s2).rename("Division")

0    0.166667
1    0.285714
2    0.375000
3    0.444444
4    0.500000
Name: Divide, dtype: float64

In [54]:
(s1 ** s2).rename("Exponentiation")

0          1
1        128
2       6561
3     262144
4    9765625
Name: Result, dtype: int64

In [55]:
(s1 // s2).rename("Floor division")

0    0
1    0
2    0
3    0
4    0
Name: Floor division, dtype: int64

In [56]:
(s1 % s2).rename("Modulus")

0    1
1    2
2    3
3    4
4    5
Name: Modulus, dtype: int64

In [59]:
s1[s1 % 2 == 0].rename("Even numbers")

1    2
3    4
Name: Even numbers, dtype: int64

In [60]:
s2[s2 % 2 != 0].rename("Odd numbers")

1    7
3    9
Name: Odd numbers, dtype: int64

### Task 5.3

You have a `Serias` object `s`. Make the following operations on this `Series` object:

* make all words in uppercase without loops;
* get length of each word without loops.

In [61]:
s = pd.Series(["numpy", "pandas", "matplotlib"])

In [63]:
s.str.upper().rename("Uppercase")

0         NUMPY
1        PANDAS
2    MATPLOTLIB
Name: Uppercase, dtype: object

In [64]:
s.str.len().rename("Length")

0     5
1     6
2    10
Name: Length, dtype: int64

## Task 6 Optional

You have a large dataset consisting of a series of numbers. Your task is to calculate the moving average of the series using a window of `5` elements. The moving average is the average of a set of consecutive values in the series, where the window `slides` through the series to compute the average at each position. The goal is to calculate the moving average efficiently and accurately. Also, compare time performance of Python and Pandas solutions.

> Please, note: If you get `nan` while calculating the moving average, you should remove it from the result. Pandas solution should take 1-2 lines of code.

### Python Solution

In the Python solution, a large dataset is generated using random numbers. The moving average is computed by iterating over the dataset using a loop. At each position, a window of 5 elements is created, and the average is calculated by summing the values in the window and dividing by 5.

In [ ]:
import random

def unknown_signature():
    # Generate a large dataset
    data = [random.randint(1, 100) for _ in range(10000000)]

    # Calculate the moving average with a window of 5
    moving_averages = []
    for i in range(4, len(data)):
        window = data[i - 4 : i + 1]
        average = sum(window) / 5
        moving_averages.append(average)
    return moving_averages[:10]

%time unknown_signature()

### Solution using Pandas and Numpy

In [68]:
arr = np.arange(1000000)
pd.Series(arr).rolling(5).mean().dropna().rename("Moving average")

4              2.0
5              3.0
6              4.0
7              5.0
8              6.0
            ...
999995    999993.0
999996    999994.0
999997    999995.0
999998    999996.0
999999    999997.0
Name: Moving average, Length: 999996, dtype: float64