# Pandas

## Task 1

You should import the necessary libraries. You will use `numpy` and `pandas` libraries.


> Don't forget to import `numpy`, and `pandas` in short form.

In [1]:
import datetime

import numpy as np
import pandas as pd

## Task 2

Create a `DataFrame` from the given dictionary `data`.

In [4]:
data = {
    "Name": ["John", "Emily", "Ryan"],
    "Age": [16, 28, 22],
    "City": ["New York", "Los Angeles", "Chicago"],
}

df = pd.DataFrame(data)

## Task 3

In this task you should complete the following steps:

### Task 3.1
Display all data for `Age` column for the DataFrame you created in the previous task.

In [5]:
df["Age"]

0    16
1    28
2    22
Name: Age, dtype: int64

### Task 3.2

Add `Salary` column to the `DataFrame` with the values `[50000, 60000, 45000]`.

In [6]:
df["Salary"] = pd.Series([50000, 60000, 45000])
df

    Name  Age         City  Salary
0   John   16     New York   50000
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

### Task 3.3

Filter the `DataFrame` to show only the rows with the `Age` greater than 18.

In [8]:
df[df["Age"] > 18]

    Name  Age         City  Salary
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

## Task 4

In this task you should complete the following steps:

### Task 4.1

Add new calculated field `Birth year`;

In [15]:
import datetime
year_now = datetime.datetime.now().year
df["Birth year"] = pd.Series(year_now - df["Age"])
df

    Name  Age         City  Salary  Birth_year  Birth year
0   John   16     New York   50000        2008        2008
1  Emily   28  Los Angeles   60000        1996        1996
2   Ryan   22      Chicago   45000        2002        2002

### Task 4.2

Add new calculated field `Average age`.

In [16]:
df["Average age"] = df["Age"].mean()
df

    Name  Age         City  Salary  Birth_year  Birth year  Average age
0   John   16     New York   50000        2008        2008         22.0
1  Emily   28  Los Angeles   60000        1996        1996         22.0
2   Ryan   22      Chicago   45000        2002        2002         22.0

### Task 4.3

Calculate absolute difference between `Age` and `Average age`.

In [18]:
(df["Age"] - df["Average age"]).abs()

0    6.0
1    6.0
2    0.0
dtype: float64

## Task 5

Complete the following tasks described below.

### Task 5.1

You have two dictionaries `data1` and `data2`. Create two `DataFrame` objects from these dictionaries. Then, `concatenate`, and `merge` these two `DataFrame` objects into one `DataFrame` object, and see the difference.

In [19]:
# Data
data1 = {'Name': ['John', 'Emily', 'Ryan'],
         'Age': [25, 28, 22]}
data2 = {'Name': ['Emily', 'Ryan', 'Mike'],
         'City': ['Los Angeles', 'Chicago', 'Houston']}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [24]:
df1.merge(df2, on="Name", how="inner")

    Name  Age         City
0  Emily   28  Los Angeles
1   Ryan   22      Chicago

In [26]:
pd.concat([df1, df2], ignore_index=True)# concatenate

    Name   Age         City
0   John  25.0          NaN
1  Emily  28.0          NaN
2   Ryan  22.0          NaN
3  Emily   NaN  Los Angeles
4   Ryan   NaN      Chicago
5   Mike   NaN      Houston

### Task 5.2

You have two `Series` objects `s1` and `s2`. Make default mathematical operations on these two `Series` objects. Such as `+`, `-`, `*`, `/`, `**`, `//`, `%`. Also, filter `s1` and print only even numbers, and `s2` only with odd numbers.

In [28]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])

In [29]:
s1 + s2

0     7
1     9
2    11
3    13
4    15
dtype: int64

In [30]:
s1 - s2

0   -5
1   -5
2   -5
3   -5
4   -5
dtype: int64

In [31]:
s1 * s2

0     6
1    14
2    24
3    36
4    50
dtype: int64

In [32]:
s1 / s2

0    0.166667
1    0.285714
2    0.375000
3    0.444444
4    0.500000
dtype: float64

In [33]:
s1 ** s2

0          1
1        128
2       6561
3     262144
4    9765625
dtype: int64

In [34]:
s1 // s2

0    0
1    0
2    0
3    0
4    0
dtype: int64

In [35]:
s1 % s2

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [36]:
s1[s1 % 2 == 0]

1    2
3    4
dtype: int64

In [37]:
s2[s2 % 2 == 1]

1    7
3    9
dtype: int64

### Task 5.3

You have a `Serias` object `s`. Make the following operations on this `Series` object:

* make all words in uppercase without loops;
* get length of each word without loops.

In [39]:
s = pd.Series(["numpy", "pandas", "matplotlib"])

In [41]:
s.str.upper()

0         NUMPY
1        PANDAS
2    MATPLOTLIB
dtype: object

In [42]:
s.str.len()

0     5
1     6
2    10
dtype: int64

## Task 6 Optional

You have a large dataset consisting of a series of numbers. Your task is to calculate the moving average of the series using a window of `5` elements. The moving average is the average of a set of consecutive values in the series, where the window `slides` through the series to compute the average at each position. The goal is to calculate the moving average efficiently and accurately. Also, compare time performance of Python and Pandas solutions.

> Please, note: If you get `nan` while calculating the moving average, you should remove it from the result. Pandas solution should take 1-2 lines of code.

### Python Solution

In the Python solution, a large dataset is generated using random numbers. The moving average is computed by iterating over the dataset using a loop. At each position, a window of 5 elements is created, and the average is calculated by summing the values in the window and dividing by 5.

In [43]:
import random

def unknown_signature():
    # Generate a large dataset
    data = [random.randint(1, 100) for _ in range(10000000)]

    # Calculate the moving average with a window of 5
    moving_averages = []
    for i in range(4, len(data)):
        window = data[i - 4 : i + 1]
        average = sum(window) / 5
        moving_averages.append(average)
    return moving_averages[:10]

%time unknown_signature()

CPU times: total: 14.4 s
Wall time: 14.4 s

[73.0, 70.4, 55.4, 53.6, 49.4, 39.6, 39.8, 40.2, 53.6, 61.4]

### Solution using Pandas and Numpy

In [47]:
def moving_average(array: np.array, size: int) -> list[float]:
    series = pd.Series(array)
    return series.rolling(size).mean().dropna().tolist()

windows_size = 5
data = np.random.randint(1, 101, size=10000000)
   
%time moving_average(data, windows_size)

CPU times: total: 797 ms
Wall time: 835 ms

[52.0,
 62.8,
 49.4,
 55.2,
 45.2,
 56.2,
 40.8,
 40.8,
 39.0,
 42.2,
 29.4,
 39.4,
 52.0,
 37.8,
 41.0,
 44.0,
 33.0,
 32.0,
 42.4,
 39.2,
 36.6,
 44.6,
 49.6,
 50.6,
 46.2,
 61.6,
 72.4,
 60.6,
 55.2,
 71.0,
 73.4,
 68.8,
 74.2,
 75.0,
 74.8,
 73.2,
 63.0,
 52.6,
 45.4,
 28.0,
 16.0,
 16.0,
 27.8,
 37.0,
 54.0,
 67.4,
 67.6,
 66.4,
 62.8,
 60.4,
 55.4,
 59.4,
 48.6,
 42.8,
 36.6,
 39.6,
 39.8,
 51.8,
 65.8,
 62.8,
 63.8,
 65.6,
 55.8,
 52.4,
 54.6,
 54.8,
 45.0,
 44.6,
 49.6,
 56.0,
 49.2,
 64.4,
 67.6,
 67.8,
 64.0,
 66.2,
 57.6,
 70.4,
 67.4,
 61.2,
 47.2,
 41.6,
 23.2,
 17.6,
 17.4,
 26.2,
 39.4,
 39.2,
 49.0,
 63.8,
 72.4,
 73.8,
 74.0,
 71.6,
 56.2,
 55.6,
 57.8,
 57.6,
 49.2,
 60.0,
 48.4,
 35.4,
 47.8,
 53.8,
 58.2,
 52.8,
 53.2,
 57.2,
 55.0,
 45.8,
 57.0,
 61.6,
 51.8,
 43.6,
 38.2,
 34.2,
 39.8,
 40.4,
 55.4,
 67.6,
 72.8,
 68.2,
 71.2,
 60.0,
 62.2,
 53.4,
 58.8,
 51.4,
 52.4,
 45.4,
 42.6,
 26.6,
 32.2,
 30.8,
 35.4,
 50.0,
 65.2,
 68.2,
 63.4,
 52.0,
 56.4,
 49.8,
 49.0,
 47.8,
 43.8,
 27.2,
 21.2,
 28.8,
 29.2,
 38.0,
 38.8,
 53.2,
 35.8,
 48.2,
 47.4,
 53.2,
 45.2,
 48.0,
 37.4,
 30.0,
 31.0,
 37.2,
 43.8,
 41.4,
 59.4,
 65.6,
 53.0,
 41.8,
 58.2,
 50.0,
 48.4,
 57.8,
 75.4,
 66.2,
 57.4,
 61.6,
 57.8,
 48.0,
 43.4,
 41.4,
 32.0,
 27.2,
 23.8,
 30.8,
 41.0,
 50.2,
 50.0,
 53.8,
 62.4,
 71.2,
 62.6,
 59.0,
 51.4,
 45.4,
 35.6,
 34.6,
 43.0,
 45.8,
 52.6,
 60.2,
 61.2,
 63.0,
 75.8,
 64.2,
 47.0,
 48.6,
 40.8,
 41.8,
 40.0,
 50.6,
 44.6,
 45.4,
 30.0,
 36.4,
 36.8,
 43.8,
 42.6,
 48.8,
 39.2,
 35.0,
 30.8,
 34.8,
 35.8,
 38.6,
 32.2,
 26.8,
 23.4,
 33.6,
 33.4,
 47.4,
 59.4,
 66.0,
 52.2,
 47.4,
 35.4,
 39.2,
 45.6,
 49.4,
 55.4,
 72.2,
 67.2,
 53.6,
 47.6,
 50.8,
 45.0,
 45.0,
 44.4,
 45.0,
 53.2,
 51.2,
 56.0,
 54.4,
 59.2,
 58.6,
 60.2,
 41.6,
 55.2,
 61.2,
 58.0,
 44.6,
 54.4,
 41.6,
 32.8,
 24.2,
 32.2,
 27.6,
 28.6,
 35.8,
 34.2,
 45.8,
 47.4,
 48.8,
 45.6,
 55.2,
 46.8,
 47.6,
 50.0,
 41.6,
 42.2,
 32.8,
 39.0,
 34.0,
 42.0,
 40.6,
 52.6,
 56.4,
 58.8,
 67.6,
 59.6,
 54.4,
 38.2,
 47.6,
 31.2,
 35.4,
 30.4,
 40.6,
 35.8,
 36.2,
 44.0,
 48.4,
 37.6,
 46.4,
 49.6,
 34.8,
 31.0,
 33.4,
 23.0,
 36.4,
 48.0,
 56.8,
 56.8,
 67.8,
 67.0,
 65.0,
 65.8,
 75.0,
 59.2,
 43.4,
 36.8,
 25.8,
 25.6,
 41.8,
 58.2,
 67.0,
 83.4,
 80.4,
 79.0,
 67.0,
 64.8,
 45.6,
 51.0,
 50.0,
 53.0,
 49.0,
 61.8,
 65.8,
 57.2,
 57.2,
 65.2,
 71.6,
 61.8,
 70.0,
 65.6,
 64.4,
 58.4,
 59.8,
 53.0,
 51.8,
 51.2,
 54.6,
 55.0,
 65.8,
 70.4,
 70.8,
 55.6,
 63.2,
 56.4,
 51.0,
 36.6,
 49.2,
 37.6,
 45.2,
 51.4,
 66.2,
 57.6,
 62.6,
 44.8,
 41.2,
 42.2,
 52.4,
 41.0,
 53.6,
 65.2,
 68.2,
 56.8,
 71.6,
 73.6,
 59.8,
 48.8,
 48.6,
 36.8,
 25.0,
 41.0,
 48.4,
 61.8,
 65.0,
 71.4,
 57.0,
 60.6,
 62.4,
 69.4,
 68.0,
 76.4,
 72.2,
 57.2,
 45.0,
 42.0,
 40.8,
 28.8,
 37.6,
 42.4,
 44.8,
 33.4,
 48.8,
 39.6,
 36.4,
 34.2,
 34.8,
 33.0,
 36.2,
 38.8,
 47.0,
 61.0,
 51.6,
 51.0,
 54.6,
 44.8,
 39.2,
 33.6,
 31.4,
 22.4,
 30.6,
 30.2,
 43.0,
 46.2,
 54.2,
 56.4,
 53.4,
 44.4,
 54.0,
 63.8,
 59.8,
 70.0,
 84.4,
 84.8,
 72.6,
 68.2,
 56.0,
 42.4,
 39.2,
 42.2,
 40.6,
 48.4,
 43.6,
 37.0,
 40.8,
 44.2,
 45.8,
 49.8,
 51.8,
 54.4,
 63.4,
 60.4,
 70.8,
 61.6,
 50.4,
 46.2,
 47.4,
 36.8,
 38.8,
 49.0,
 37.6,
 28.4,
 41.0,
 46.8,
 39.4,
 50.0,
 61.4,
 58.8,
 59.6,
 52.6,
 44.4,
 32.8,
 21.2,
 16.4,
 22.6,
 29.8,
 28.8,
 32.6,
 47.0,
 42.2,
 49.6,
 60.8,
 58.0,
 58.4,
 65.6,
 65.6,
 63.2,
 77.8,
 60.8,
 70.2,
 56.2,
 56.4,
 46.8,
 63.0,
 60.2,
 68.4,
 75.6,
 74.8,
 64.0,
 58.0,
 56.6,
 40.0,
 42.4,
 53.6,
 62.0,
 63.4,
 80.8,
 79.6,
 78.0,
 69.8,
 74.6,
 64.6,
 69.6,
 70.2,
 70.6,
 57.4,
 49.2,
 48.4,
 39.4,
 47.6,
 55.8,
 67.8,
 67.2,
 61.6,
 56.4,
 62.0,
 64.8,
 51.4,
 56.4,
 57.6,
 53.8,
 49.2,
 51.2,
 44.6,
 41.0,
 39.2,
 31.6,
 47.0,
 49.2,
 41.0,
 28.2,
 39.8,
 27.8,
 33.8,
 32.0,
 34.4,
 25.0,
 38.6,
 36.6,
 54.4,
 52.8,
 56.0,
 48.4,
 53.8,
 46.0,
 61.6,
 53.4,
 54.0,
 56.0,
 53.0,
 45.0,
 56.4,
 49.0,
 43.8,
 42.0,
 38.4,
 34.2,
 45.4,
 53.8,
 55.6,
 51.0,
 50.2,
 46.0,
 41.2,
 41.2,
 57.4,
 57.2,
 54.2,
 43.2,
 49.6,
 52.4,
 56.8,
 51.6,
 55.8,
 42.6,
 27.6,
 18.6,
 28.4,
 34.4,
 47.2,
 54.2,
 58.8,
 54.6,
 44.8,
 41.0,
 42.2,
 42.8,
 38.4,
 49.6,
 57.0,
 59.8,
 64.0,
 79.2,
 76.6,
 72.6,
 64.4,
 65.2,
 61.4,
 56.6,
 51.6,
 59.4,
 63.6,
 57.6,
 70.0,
 74.8,
 77.4,
 62.6,
 70.2,
 63.8,
 64.4,
 52.2,
 66.0,
 67.2,
 64.6,
 66.2,
 68.4,
 54.8,
 52.8,
 47.2,
 34.8,
 41.4,
 49.8,
 43.0,
 45.8,
 61.8,
 65.0,
 64.6,
 72.6,
 77.4,
 66.6,
 65.2,
 71.2,
 62.2,
 51.0,
 56.6,
 49.8,
 37.4,
 46.6,
 55.6,
 45.4,
 51.2,
 59.4,
 55.4,
 54.0,
 65.8,
 67.4,
 64.6,
 56.8,
 66.4,
 58.4,
 51.2,
 59.6,
 70.4,
 59.2,
 53.2,
 47.6,
 46.6,
 44.2,
 49.0,
 50.2,
 52.4,
 38.6,
 39.8,
 41.6,
 54.4,
 65.4,
 80.8,
 82.4,
 70.0,
 72.2,
 69.8,
 55.8,
 46.8,
 61.4,
 52.2,
 50.6,
 48.6,
 45.2,
 47.8,
 40.6,
 34.4,
 46.0,
 46.6,
 44.2,
 43.0,
 39.0,
 42.8,
 40.6,
 39.4,
 46.4,
 56.2,
 48.8,
 55.0,
 43.2,
 53.0,
 54.2,
 59.2,
 62.2,
 70.4,
 63.6,
 67.8,
 54.2,
 42.8,
 33.0,
 31.0,
 28.0,
 29.6,
 29.6,
 36.6,
 45.2,
 49.6,
 66.2,
 71.2,
 78.0,
 76.4,
 62.0,
 61.6,
 73.2,
 77.2,
 81.0,
 79.4,
 68.0,
 65.6,
 47.0,
 41.2,
 40.0,
 45.8,
 36.2,
 53.6,
 45.6,
 59.6,
 65.8,
 74.6,
 71.6,
 82.4,
 68.8,
 55.8,
 60.0,
 61.0,
 49.2,
 49.2,
 49.6,
 46.8,
 35.2,
 39.8,
 55.0,
 61.4,
 50.0,
 62.4,
 65.2,
 62.8,
 66.8,
 78.0,
 76.2,
 67.8,
 64.0,
 52.2,
 45.8,
 46.0,
 49.4,
 39.0,
 33.6,
 35.6,
 35.6,
 35.6,
 41.6,
 49.2,
 49.2,
 37.2,
 35.4,
 40.2,
 40.2,
 38.6,
 40.6,
 41.4,
 31.8,
 28.8,
 36.0,
 36.4,
 50.8,
 58.2,
 65.0,
 50.6,
 64.6,
 49.0,
 57.4,
 48.0,
 59.6,
 47.6,
 46.4,
 46.0,
 49.8,
 40.0,
 40.4,
 45.8,
 37.2,
 38.8,
 37.2,
 31.0,
 37.0,
 39.8,
 48.6,
 63.2,
 64.4,
 60.8,
 68.4,
 63.4,
 53.6,
 69.8,
 67.8,
 52.6,
 43.4,
 46.6,
 42.2,
 33.6,
 33.6,
 36.6,
 27.2,
 29.8,
 38.2,
 38.8,
 36.4,
 53.4,
 39.8,
 43.6,
 54.6,
 56.4,
 51.0,
 57.2,
 55.6,
 47.6,
 54.6,
 53.0,
 50.4,
 49.8,
 41.8,
 41.6,
 47.2,
 50.2,
 52.8,
 66.0,
 72.2,
 57.8,
 59.8,
 61.6,
 60.4,
 43.0,
 40.6,
 32.4,
 26.2,
 33.0,
 34.0,
 52.0,
 57.2,
 66.2,
 60.2,
 64.6,
 49.2,
 58.0,
 47.4,
 53.6,
 67.0,
 66.2,
 57.0,
 58.6,
 44.2,
 37.2,
 46.6,
 56.2,
 64.6,
 63.8,
 68.2,
 58.4,
 55.0,
 51.6,
 57.6,
 42.4,
 52.6,
 55.0,
 50.6,
 40.6,
 53.2,
 51.4,
 41.6,
 40.2,
 58.2,
 45.6,
 36.8,
 34.6,
 41.0,
 26.2,
 41.2,
 58.2,
 55.0,
 47.0,
 57.2,
 43.8,
 45.2,
 44.2,
 47.4,
 52.0,
 66.0,
 63.6,
 68.6,
 60.0,
 45.0,
 45.2,
 36.4,
 40.6,
 46.0,
 56.2,
 48.0,
 57.0,
 49.4,
 48.0,
 45.0,
 47.2,
 33.2,
 45.4,
 41.8,
 38.4,
 40.8,
 40.8,
 32.2,
 37.8,
 43.4,
 42.4,
 41.4,
 48.8,
 45.0,
 32.6,
 30.2,
 46.2,
 38.8,
 50.0,
 54.4,
 52.2,
 50.2,
 59.0,
 52.8,
 63.4,
 55.8,
 57.8,
 46.0,
 46.8,
 39.8,
 54.8,
 49.4,
 64.4,
 71.4,
 77.4,
 65.2,
 57.6,
 48.6,
 52.4,
 42.0,
 47.2,
 55.0,
 57.0,
 52.8,
 54.0,
 63.2,
 67.2,
 59.2,
 54.6,
 54.4,
 50.8,
 48.6,
 61.2,
 57.2,
 58.0,
 46.2,
 37.8,
 33.0,
 42.6,
 47.4,
 56.4,
 60.0,
 62.6,
 62.2,
 68.6,
 76.6,
 74.6,
 68.2,
 64.2,
 60.6,
 56.8,
 48.6,
 47.6,
 ...]